ROLE_SUPERADMIN = "SUPERADMIN"
ROLE_ADMIN = "ADMIN"
ROLE_USER = "USER"

GROUP_SUPERADMIN = "SuperAdmin"
GROUP_ADMIN = "Admin"
GROUP_USER = "User"

ROLE_TO_GROUP = {
    ROLE_SUPERADMIN: GROUP_SUPERADMIN,
    ROLE_ADMIN: GROUP_ADMIN,
    ROLE_USER: GROUP_USER,
}
